---
- hosts: all
  tasks:
    - stat: path=~/.bash_history
      register: bash_history

    - stat: path={{ backup_path }}/bash_history
      register: backup_bash_history

    - set_fact: newer_bash_history={{ backup_bash_history.stat.exists and bash_history.stat.ctime > backup_bash_history.stat.ctime }}

    - file: path={{ backup_path }}/bash_history state=absent
      when: newer_bash_history

    - pause: seconds=10
      when: newer_bash_history

    - copy: src=~/.bash_history dest={{ backup_path }}/bash_history
      when: newer_bash_history or not backup_bash_history.stat.exists

    - synchronize: src=~/.ssh/ dest={{ backup_path }}/ssh times=yes recursive=yes rsync_opts="-u"

    # - file: path={{ backup_path }}/gpg state=directory
    # - name: Backup GPG key
    #   shell: >
    #     gpg -a --export {{ item }} > {{ backup_path }}/gpg/public_{{ item }}.key &&
    #     gpg -a --export-secret-keys {{ item }} > {{ backup_path }}/gpg/private_{{ item }}.key &&
    #     gpg --export-ownertrust > {{ backup_path }}/gpg/ownertrust.txt
    #   with_items:
    #     - exaspark@gmail.com
