---
- hosts: all
  tasks:
    - lineinfile:
        dest: "/etc/syslog.conf"
        regexp: 'cron\.\* '
        line: "cron.*      /var/log/syslog.cron.log"
      become: yes
      become_method: sudo
    - shell: >
        launchctl unload /System/Library/LaunchDaemons/com.apple.syslogd.plist &&
        launchctl load /System/Library/LaunchDaemons/com.apple.syslogd.plist
      become: yes
      become_method: sudo

    - cron:
        name: "Backup configs"
        minute: "0" # every hour
        job: >
          /bin/zsh -c
          "source ~/.zshrc &&
          cd {{ curdir }} &&
          ansible-playbook ansible/backup.yml -i ansible/local -e backup_path={{ lookup('env', 'BACKUP_PATH') }} 2>&1 |
          /usr/bin/logger -p cron.info"
          > /dev/null

    - shell: gpg --import {{ lookup('env', 'BACKUP_PATH') }}/gpg/private_exaspark@gmail.com.key
    - shell: gpg --import-ownertrust {{ lookup('env', 'BACKUP_PATH') }}/gpg/ownertrust.txt
