---
- hosts: all
  tasks:
    - cron:
        name: "Backup configs"
        minute: "0" # every hour
        job: >
          /bin/bash -c
          "source ~/.bashrc &&
          cd {{ curdir }} &&
          ansible-playbook ansible/backup.yml -i ansible/local -e backup_path={{ lookup('env', 'BACKUP_PATH') }} 2>&1"
