---
- hosts: all
  tasks:
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - zlib
        - sqlite

    - shell: |
        if ! [[ "$(asdf plugin list | grep python)" ]] ; then
          asdf plugin-add python https://github.com/danhper/asdf-python.git
        fi
    - shell: "asdf install python {{ version }}"
    - shell: "asdf global python {{ version }}"
