---
- hosts: all
  tasks:
    - shell: |
        if ! [[ "$(brew ls --versions jq)" ]] ; then
          brew install jq
        fi
    - shell: |
        if ! [[ "asdf plugin list | grep java" ]] ; then
          asdf plugin-add java https://github.com/halcyon/asdf-java.git
        fi
    - shell: "asdf install java {{ version }}"
