---
- hosts: all
  tasks:
    - file: path=/etc/zprofile state=absent
      become: yes
      become_method: sudo

    - file: path=~/.bundle state=directory
    - file: path=~/.zsh state=directory
    - file: path=~/.zsh/custom state=directory
    - file: path=~/.gnupg state=directory
    - file: path=~/.vim-snippets state=directory
    - file: src={{ curdir }}/{{ item }} dest=~/.{{ item }} state=link force=yes
      with_items:
        - asdfrc
        - ansible.cfg
        - bundle/config
        - gnupg/gpg-agent.conf
        - irbrc
        - gemrc
        - gitconfig
        - gitignore
        - pryrc
        - vim-snippets/coffee.snippets
        - vim-snippets/html.snippets
        - vim-snippets/javascript.snippets
        - vim-snippets/ruby.snippets
        - zshenv
        - zshrc
        - zsh/custom/aliases.zsh
        - sshrc
        - tern-project
        - ctags
        - iex.exs

    - file: src={{ curdir }}/zsh/themes/exaspark.zsh-theme dest=~/.oh-my-zsh/themes/exaspark.zsh-theme state=link
    - git: repo=https://github.com/zsh-users/zsh-autosuggestions.git dest=~/.zsh/zsh-autosuggestions clone=yes update=no

    - file: path=~/.sshrc.d state=directory
    - file: src={{ curdir }}/zsh/custom/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - aliases.zsh
    - file: src={{ curdir }}/{{ item }} dest=~/.sshrc.d/{{ item }} state=link
      with_items:
        - vimrc
        - irbrc

    - file: path=~/.config/kitty state=directory
    - file: src={{ curdir }}/kitty.conf dest=~/.config/kitty/kitty.conf state=link force=yes

    - file: path=~/.config/nvim state=directory
    - file: src={{ curdir }}/coc-settings.json dest=~/.config/nvim/coc-settings.json state=link force=yes

    - file: path=~/.config/coc/extensions state=directory
    - file: src={{ curdir }}/coc-package.json dest=~/.config/coc/extensions/package.json state=link force=yes
