---
- hosts: all
  tasks:
    - shell: |
        if ! [[ "$(asdf plugin list | grep ruby)" ]] ; then
          asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
        fi
    - shell: "asdf install ruby {{ version }}"
    - shell: "asdf global ruby {{ version }}"

    - name: Install bundler
      shell: gem install bundler
      environment:
        ASDF_RUBY_VERSION: "{{ version }}"

    - name: Install gem neovim for deoplete.vim
      shell: gem install neovim
      become: true # should be installed via sudo
      environment:
        ASDF_RUBY_VERSION: "{{ version }}"

    - name: Install gem solargraph for coc.nvim
      shell: gem install solargraph
      environment:
        ASDF_RUBY_VERSION: "{{ version }}"

    - name: Install gem gem-ctags
      shell: gem install gem-ctags
      environment:
        ASDF_RUBY_VERSION: "{{ version }}"

    # better than ctags, supports Module::Class
    - shell: gem install ripper-tags
      environment:
        ASDF_RUBY_VERSION: "{{ version }}"
