---
- hosts: all
  tasks:
    - shell: brew update
    - shell: brew tap homebrew/services # e.g. allow 'brew services start mysql' command

    # alt
    - shell: brew tap "codebreakdown/homebrew-oss"
    - shell: brew install codebreakdown/oss/alt

    - shell: brew tap "brew tap espanso/espanso"
    - shell: brew install espanso # requires pressing "opt+cmd+s" (toggle_macos_secure_keyboard_entry) in Kitty on MacOS

    - shell: |
        if ! xcode-select -p | grep CommandLineTools ; then
          xcode-select --install
        fi

    # apps
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - git
        - openssl
        - cmake
        - ctags
        - imagemagick
        - ripgrep
        - fd # faster than find
        - wget
        - fzf
        - unar
        - gnu-tar # for Ansible unarchive module
        - gnu-sed # for spectre-nvim
        - mas # mac app store cli
        - jid
        - ffmpeg
        - rsync
        - trash
        - pstree
        - watch # gnu
        - stern # kube logs
        - jq
        - sops
        # - doctl
        - awscli
        - tidy-html5
        - dokku/repo/dokku
        - argocd
        - gh

    # to avoid using flag --with-openssl-dir=/usr/local/opt/openssl
    - shell: brew link --force openssl

    # heroku
    # - shell: brew tap heroku/brew && brew install heroku

    # services
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
          ln -sfv /usr/local/opt/{{ item }}/*.plist ~/Library/LaunchAgents
        fi
      with_items:
        - postgresql
        - redis

    # postgresql
    - shell: createuser -s postgres
      ignore_errors: true

    # sshrc << not packaged
    - shell: curl https://raw.githubusercontent.com/exAspArk/sshrc/master/sshrc -o ~/Downloads/sshrc
    - shell: chmod +x ~/Downloads/sshrc && mv ~/Downloads/sshrc /usr/local/bin
      become: true

    # fonts
    - shell: brew tap homebrew/cask-fonts
    - shell: brew install --cask font-fira-code
