---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    # brave
    - shell: apt install apt-transport-https curl
    - shell: curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
    - shell: echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
    - shell: apt update && apt install brave-browser

    # kitty << not packaged
    - shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
    - shell: ln -s ~/.local/kitty.app/bin/kitty /usr/local/bin/kitty
    - shell: cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications
    - shell: sed -i "s/Icon\=kitty/Icon\=\/home\/$USER\/.local\/kitty.app\/share\/icons\/hicolor\/256x256\/apps\/kitty.png/g" ~/.local/share/applications/kitty.desktop

    # yarn
    - shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - shell: apt update && apt install yarn

    # gpg
    - shell: apt install gpg2
    - shell: gpg --import {{ backup_path }}/gpg/private_exaspark@gmail.com.key
    - shell: gpg --import-ownertrust {{ backup_path }}/gpg/ownertrust.txt

    # brew
    - shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    - shell: echo "eval \$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" >> ~/.profile

    # python
    - shell: asdf plugin-add python https://github.com/danhper/asdf-python.git
    - shell: asdf install python 3.8.1
    - shell: apt install libsqlite3-dev # for gcloud before installing python 2
    - shell: asdf install python 2.7.17
    - shell: asdf global python 3.8.1 2.7.17
