---
- hosts: all
  tasks:
    - shell: brew update
    - shell: brew tap homebrew/services # e.g. allow 'brew services start mysql' command

    # alt
    - shell: brew tap "codebreakdown/homebrew-oss"
    - shell: brew install codebreakdown/oss/alt

    - shell: |
        if ! xcode-select -p | grep CommandLineTools ; then
          xcode-select --install
        fi

    # apps
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - git
        - openssl
        - cmake
        - ctags
        - imagemagick
        - ripgrep
        - wget
        - fzf
        - unar
        - findutils # to use gfind with -print option
        - gnu-tar # for Ansible unarchive module
        - mas # mac app store cli
        - jid
        - ffmpeg
        - rsync
        - trash
        - pstree
        - watch # gnu
        - sshfs
        - stern # kube logs
        - jq
        - sops

    # to avoid using flag --with-openssl-dir=/usr/local/opt/openssl
    - shell: brew link --force openssl

    # services
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
          ln -sfv /usr/local/opt/{{ item }}/*.plist ~/Library/LaunchAgents
        fi
      with_items:
        - postgresql
        - redis

    # postgresql
    - shell: createuser -s postgres
      ignore_errors: true

    # sshrc << not packaged
    - shell: curl https://raw.githubusercontent.com/exAspArk/sshrc/master/sshrc -o ~/Downloads/sshrc
    - shell: chmod +x ~/Downloads/sshrc && mv ~/Downloads/sshrc /usr/local/bin
