---
- hosts: all
  tasks:
    - shell: |
        if ! [[ "$(eval "brew list --cask | grep '^{{ item }}$'")" ]] ; then
          brew install --cask {{ item }}
        fi
      with_items:
        - google-chrome
        - sourcetree
        - the-unarchiver
        - licecap # record gifs from screen
        - android-file-transfer
        - paragon-ntfs
        - keeweb
        - zoom
        - moom
        - osxfuse
        - insomnia
        - tableplus # sql GUI vs psequel
        - slack
        - gpg-suite
        - ngrok
        - kitty
        - docker
        - qbittorrent
        - karabiner-elements
        - obsidian
        - syncthing
        - raycast
        - bartender
        - betterdisplay # fix macOS Ventura display scale bug
        - blackhole-2ch # pass audio output as input to another app
        # - keybase
        # - google-cloud-sdk # gcloud
        # - keycastr # show keystrokes
        # - sqlitebrowser
        # - tunnelblick
        # - sequel-pro # mysql
        # - psequel # postgres
        # - libreoffice
        # - cyberduck
        # - rescuetime
        # - franz
        # - ccmenu
        # - minikube
        # - mist # ethereum

    - shell: brew install sshfs

    # - shell: gcloud components install kubectl

    - shell: |
        if ! mas list | grep {{ item }}; then
          mas install $(mas search '{{ item }}' | awk '{print $1}' | head -1)
        fi
      with_items:
        - Keynote
        - Spark
        - Xcode
        - Polarr
        - Elmedia Video Player
        - VPN Unlimited
        - Yubico Authenticator
        - Flycut
        - WhatsApp
