---
- hosts: all
  tasks:
    - shell: |
        if ! [[ "$(eval "brew cask list | grep '^{{ item }}$'")" ]] ; then
          brew cask install {{ item }}
        fi
      with_items:
        - sourcetree
        - jumpcut
        - the-unarchiver
        - mplayerx
        - licecap # record gifs from screen
        - android-file-transfer
        - paragon-ntfs
        - keeweb
        - zoomus
        - typora
        - spectacle
        - go2shell
        - purevpn
        - keycastr # show keystrokes
        - osxfuse
        - insomnia
        - tableplus # sql GUI vs psequel
        - slack
        - qbittorrent
        - gpg-suite
        - graphql-playground
        - google-chrome
        - google-cloud-sdk # gcloud
        # - sqlitebrowser
        # - skype
        # - tunnelblick
        # - sequel-pro # mysql
        # - psequel # postgres
        # - libreoffice
        # - cyberduck
        # - rescuetime
        # - franz
        # - ccmenu
        # - minikube
        # - google-cloud-sdk # requires Python2
        # - mist # ethereum

    - shell: |
        if ! mas list | grep {{ item }}; then
          mas install $(mas search '{{ item }}' | awk '{print $1}' | head -1)
        fi
      with_items:
        - Simplenote
        - Pocket
        - Keynote
        - Spark
        - Xcode
        # - Monosnap
        # - Twitter
