---
- hosts: all
  tasks:
    # brew
    - shell: brew -v
      register: brew_exists
      ignore_errors: yes
    - get_url: url=https://raw.githubusercontent.com/Homebrew/install/master/install dest=/tmp/homebrew_install.rb
      when: brew_exists|failed
    - shell: ruby /tmp/homebrew_install.rb
      when: brew_exists|failed
    - file: path=/tmp/homebrew_install.rb state=absent
      when: brew_exists|failed

    - shell: |
        if ! [[ "$(eval "brew cask list | grep '^{{ item }}$'")" ]] ; then
          brew cask install {{ item }}
        fi
      with_items:
        - brave-browser
        - dropbox

    # oh my zsh
    - shell: echo $ZSH_VERSION
      ignore_errors: yes
    - get_url: url=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh dest=/tmp/oh_my_zsh_install.sh mode=0744
      when: zsh_version is undefined
    - shell: sh -c /tmp/oh_my_zsh_install.sh
      when: zsh_version is undefined
    - shell: rm /tmp/oh_my_zsh_install.sh
      when: zsh_version is undefined

    # asdf and yarn
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - asdf
        - zlib # for asdf python
        - sqlite # for asdf python
        - yarn
        - 'neovim/neovim/neovim'

    - shell: gpg --import {{ backup_path }}/gpg/private_exaspark@gmail.com.key
    - shell: gpg --import-ownertrust {{ backup_path }}/gpg/ownertrust.txt

    # python
    - shell: asdf plugin-add python https://github.com/danhper/asdf-python.git
    - shell: asdf install python 3.7.3
    - shell: asdf install python 2.7.16
    - shell: asdf global python 3.7.3 2.7.16
