---
- hosts: all
  tasks:
    # oh my zsh
    - shell: echo $ZSH_VERSION
      ignore_errors: yes
    - get_url: url=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh dest=/tmp/oh_my_zsh_install.sh mode=0744
      when: zsh_version is undefined
    - shell: sh -c /tmp/oh_my_zsh_install.sh
      when: zsh_version is undefined
    - shell: rm /tmp/oh_my_zsh_install.sh
      when: zsh_version is undefined

    # asdf and yarn
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - asdf
        - zlib # for asdf python
        - sqlite # for asdf python
        - yarn
        - 'neovim/neovim/neovim'

    - shell: |
        if ! [[ "$(eval "brew cask list | grep '^{{ item }}$'")" ]] ; then
          brew cask install {{ item }}
        fi
      with_items:
        - brave-browser

    # python
    - shell: asdf plugin-add python https://github.com/danhper/asdf-python.git
    - shell: asdf install python 3.7.3
    - shell: asdf install python 2.7.16
    - shell: asdf global python 3.7.3 2.7.16
