---
- hosts: all
  tasks:
    # oh my zsh
    - shell: echo $ZSH_VERSION
      ignore_errors: yes
      register: zsh_version
    - get_url: url=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh dest=/tmp/oh_my_zsh_install.sh mode=0744
      when: zsh_version is undefined
    - shell: sh -c /tmp/oh_my_zsh_install.sh
      when: zsh_version is undefined
    - shell: rm /tmp/oh_my_zsh_install.sh
      when: zsh_version is undefined
    - shell: compaudit | xargs chmod g-w,o-w
      when: zsh_version is undefined

    # asdf and yarn
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - asdf
        - yarn
        - 'neovim/neovim/neovim'

    - shell: |
        if ! [[ "$(eval "brew list --cask | grep '^{{ item }}$'")" ]] ; then
          brew install --cask {{ item }}
        fi
      with_items:
        - eloston-chromium
        - keeweb
        - dropbox

    - shell: 'defaults write com.apple.Finder AppleShowAllFiles true'
    - shell: 'killall Finder'
